# Generated by Django 4.0.1 on 2022-01-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stars',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
