# Generated by Django 4.0.3 on 2022-04-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='plot',
            new_name='density',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_dol',
        ),
        migrations.AddField(
            model_name='product',
            name='price_sum',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
