# Generated by Django 4.0.3 on 2022-04-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_plot_product_density_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_sum',
        ),
    ]
