# Generated by Django 4.0.3 on 2022-04-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('долларов', 'долларов'), ('евро', 'евро'), ('рубль', 'рубль')], max_length=100, verbose_name='валюта')),
                ('summa', models.PositiveBigIntegerField(verbose_name='сумма')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
    ]
