# Generated by Django 4.0.3 on 2022-04-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='currency',
            new_name='currency_type',
        ),
    ]
