# Generated by Django 4.0.3 on 2022-04-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_currency_currency_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='summa',
            field=models.PositiveBigIntegerField(verbose_name='UZS'),
        ),
    ]
