# Generated by Django 4.0.3 on 2022-04-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_currency_summa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
